const SibApiV3Sdk = require('sib-api-v3-sdk');

const PDFDocument = require('pdfkit');

const generatePayslipPDF = (name, month, year, netSalary, baseSalary, presentDays, totalDays, payPerDay) => {
    console.log("Generating PDF for:", name);
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
        const buffers = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
            const pdfData = Buffer.concat(buffers);
            resolve(pdfData.toString('base64'));
        });

        // Header
        doc.fontSize(20).text('Payslip', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`For the month of ${month} ${year}`, { align: 'center' });
        doc.moveDown();
        doc.moveDown();

        // Employee Info
        doc.fontSize(14).text(`Employee Name: ${name}`);
        doc.moveDown();

        // Table-like Structure
        const startX = 50;
        let currentY = doc.y;

        const drawRow = (label, value, isBold = false) => {
            doc.fontSize(12).font(isBold ? 'Helvetica-Bold' : 'Helvetica').text(label, startX, currentY);
            doc.text(value, 300, currentY, { align: 'right' });
            currentY += 20;
        };

        drawRow('Working Days', `${presentDays} / ${totalDays}`);
        drawRow('Pay Per Day', `₹${parseInt(payPerDay).toLocaleString()}`);
        drawRow('Base Salary', `₹${baseSalary.toLocaleString()}`);
        
        doc.moveTo(startX, currentY).lineTo(550, currentY).stroke();
        currentY += 10;
        
        drawRow('Net Pay', `₹${netSalary.toLocaleString()}`, true);

        // Footer
        doc.moveDown();
        doc.moveDown();
        doc.fontSize(10).text('Generated by Velora CRM', { align: 'center', color: 'grey' });

        doc.end();
        } catch (err) {
            reject(err);
        }
    });
};

const sendPayslipEmail = async (email, name, month, year, netSalary, baseSalary, presentDays, totalDays, payPerDay) => {
  const defaultClient = SibApiV3Sdk.ApiClient.instance;
  const apiKey = defaultClient.authentications['api-key'];
  
  if (!process.env.BREVO_API_KEY) {
      console.warn("BREVO_API_KEY is missing in environment variables. Skipping email.");
      return false;
  }
  
  apiKey.apiKey = process.env.BREVO_API_KEY;

  const apiInstance = new SibApiV3Sdk.TransactionalEmailsApi();

  // Generate PDF
  let pdfBase64;
  try {
      pdfBase64 = await generatePayslipPDF(name, month, year, netSalary, baseSalary, presentDays, totalDays, payPerDay);
  } catch (pdfErr) {
      console.error("Error generating PDF:", pdfErr);
      // Proceed without attachment if PDF generation fails, or return false? 
      // Let's log and proceed for now, but usually we'd want to fail or alert.
  }

  const sendSmtpEmail = new SibApiV3Sdk.SendSmtpEmail();
  sendSmtpEmail.subject = `Payslip Generated - ${month} ${year}`;
  
  // Attach PDF if generated
  if (pdfBase64) {
      sendSmtpEmail.attachment = [
          {
              content: pdfBase64,
              name: `Payslip_${month}_${year}.pdf`
          }
      ];
  }

  // Premium HTML Email Template
  sendSmtpEmail.htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8fafc; border-radius: 16px;">
        <div style="background-color: #ffffff; padding: 40px; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
            <div style="text-align: center; margin-bottom: 25px;">
                <div style="display: inline-block; width: 60px; height: 60px; line-height: 60px; text-align: center; border-radius: 14px; background: linear-gradient(135deg, #0f172a 0%, #0b132b 100%); position: relative; box-shadow: 0 4px 10px rgba(15, 23, 42, 0.15); margin: 0 auto;">
                    <svg width="28" height="28" viewBox="0 0 100 100" style="vertical-align: middle;">
                        <polygon points="15,20 45,20 50,75 30,85" fill="#0ea5e9" opacity="0.8"/>
                        <polygon points="45,20 50,75 65,48" fill="#0284c7" opacity="0.95"/>
                        <polygon points="65,48 50,75 85,20 75,15" fill="#14b8a6" opacity="0.9"/>
                    </svg>
                </div>
                <div style="font-family: 'Georgia', serif; font-size: 16px; font-weight: bold; letter-spacing: 3px; color: #0f172a; margin-top: 10px; text-transform: uppercase;">Velora</div>
                <h2 style="color: #1e293b; margin-top: 15px; margin-bottom: 5px;">Payslip Generated</h2>
                <p style="color: #64748b; margin: 0;">For ${month} ${year}</p>
            </div>
            
            <div style="border-top: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; padding: 20px 0; margin-bottom: 30px;">
                <p style="color: #334155; font-size: 16px; margin-bottom: 20px;">Hello <b>${name}</b>,</p>
                <p style="color: #64748b; line-height: 1.6;">Please find your payslip attached for <b>${month} ${year}</b>.</p>
                <p style="color: #64748b; font-size: 14px;">(A detailed breakdown is also provided below)</p>
                
                <table style="width: 100%; margin-top: 20px; border-collapse: collapse;">
                    <tr style="background-color: #f8fafc;">
                        <td style="padding: 12px; color: #64748b; font-size: 14px; border-radius: 8px 0 0 8px;">Working Days</td>
                        <td style="padding: 12px; color: #0f172a; font-weight: bold; text-align: right; border-radius: 0 8px 8px 0;">${presentDays} / ${totalDays}</td>
                    </tr>
                     <tr><td colspan="2" style="height: 5px;"></td></tr>
                     <tr style="background-color: #f8fafc;">
                        <td style="padding: 12px; color: #64748b; font-size: 14px; border-radius: 8px 0 0 8px;">Pay Per Day</td>
                        <td style="padding: 12px; color: #0f172a; font-weight: bold; text-align: right; border-radius: 0 8px 8px 0;">₹${parseInt(payPerDay).toLocaleString()}</td>
                    </tr>
                    <tr><td colspan="2" style="height: 5px;"></td></tr>
                    <tr style="background-color: #f8fafc;">
                        <td style="padding: 12px; color: #64748b; font-size: 14px; border-radius: 8px 0 0 8px;">Base Salary</td>
                        <td style="padding: 12px; color: #0f172a; font-weight: bold; text-align: right; border-radius: 0 8px 8px 0;">₹${baseSalary.toLocaleString()}</td>
                    </tr>
                    <tr><td colspan="2" style="height: 10px;"></td></tr>
                    <tr style="background-color: #f0fdf4;">
                        <td style="padding: 12px; color: #166534; font-size: 14px; font-weight: bold; border-radius: 8px 0 0 8px;">Net Pay</td>
                        <td style="padding: 12px; color: #15803d; font-weight: bold; font-size: 18px; text-align: right; border-radius: 0 8px 8px 0;">₹${netSalary.toLocaleString()}</td>
                    </tr>
                </table>
            </div>

            <p style="text-align: center; color: #94a3b8; font-size: 12px; margin-top: 30px;">
                This is an automated message. Please do not reply to this email.
            </p>
        </div>
    </div>
  `;
  
  sendSmtpEmail.sender = { "name": "Velora CRM", "email": process.env.SENDER_EMAIL || "no-reply@veloracrm.com" };
  sendSmtpEmail.to = [{ "email": email, "name": name }];

  try {
    const data = await apiInstance.sendTransacEmail(sendSmtpEmail);
    console.log('Payslip Email sent successfully.');
    return true;
  } catch (error) {
    console.error('Error sending payslip email:', error);
    return false;
  }
};

module.exports = { sendPayslipEmail };
